/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Ventanas.*;

/**
 *
 * @author ADMIN
 */
public class Admin_Options extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Login
     */
    public Admin_Options() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Admin_Image = new javax.swing.JLabel();
        btn_Volver = new javax.swing.JButton();
        btn_Usuarios = new javax.swing.JButton();
        btn_Comidas = new javax.swing.JButton();
        btn_Restaurant = new javax.swing.JButton();
        lbl_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Admin_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Admin.png"))); // NOI18N
        getContentPane().add(Admin_Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 200, 170));

        btn_Volver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Volver.setText("Volver");
        btn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VolverActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, -1, -1));

        btn_Usuarios.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        btn_Usuarios.setText("Usuarios");
        btn_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 160, 40));

        btn_Comidas.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        btn_Comidas.setText("Comidas");
        btn_Comidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ComidasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Comidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 160, 40));

        btn_Restaurant.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        btn_Restaurant.setText("Restaurantes");
        btn_Restaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RestaurantActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Restaurant, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 160, 40));

        lbl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(lbl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 387, 488));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RestaurantActionPerformed
        
        new Restaurants_Options().setVisible(true);
        
    }//GEN-LAST:event_btn_RestaurantActionPerformed

    private void btn_ComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ComidasActionPerformed
        
        new Food_Options().setVisible(true);
        
    }//GEN-LAST:event_btn_ComidasActionPerformed

    private void btn_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UsuariosActionPerformed
        
         new Users_Options().setVisible(true);     
    }//GEN-LAST:event_btn_UsuariosActionPerformed

    private void btn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VolverActionPerformed
        
        this.setVisible(false);
        
    }//GEN-LAST:event_btn_VolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Options().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin_Image;
    private javax.swing.JButton btn_Comidas;
    private javax.swing.JButton btn_Restaurant;
    private javax.swing.JButton btn_Usuarios;
    private javax.swing.JButton btn_Volver;
    private javax.swing.JLabel lbl_Fondo;
    // End of variables declaration//GEN-END:variables
}
